<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
$oplata = Mage::getModel('FondyOnPage/FondyOnPage');
$data = $oplata->getFormFields();
?>
<script src="https://api.fondy.eu/static_common/v1/checkout/ipsp.js"></script>
<style>
    .col3-layout .col-wrapper .col-main {
         width: 100%;
    }
	#checkout_message{
		 font-size: 14px;
		 color: red;
	}
    #checkout_mess {
        font-size: 25px;
        color: red;
        text-align: center;
    }
    #checkout_button{
        width: 200px;
        float: right;
        padding:25px;
        text-align:center;
        cursor:pointer;
        background: #62ba46;
        color:#fff;
    &:hover{
         background-color:red;
     }
    }
    #checkout_button_cancel{
        margin-right: 10px;
        width: 200px;
        float: right;
        padding:25px;
        text-align:center;
        cursor:pointer;
        background: silver;
        color:#fff;
    &:hover{
         background-color:white;
     }
    }
    #checkout_wrapper {
		min-height:500px;
		text-align: left;
        position: relative;
        background: #FFF;
        /* padding: 30px; */
        padding-left: 15px;
        padding-right: 15px;
        padding-bottom: 30px;
        width: 100%;
        height: auto;
        max-width: 2000px;
        margin: 9px auto;
    }
</style>
<div id="checkout">
    <div id="checkout_wrapper">
	<?php if ($data['error'] == true){echo $data['message'];}?>
    </div>
</div>

<script>
    var checkoutStyles = {
        "html , body" : {
            "overflow" : "hidden",
            "height" : "auto"
        },
		".pages-checkout .page-section-overview .order-amount .txt-amount" : {
            "font-size" : "14px"
        },
		".pages-checkout .page-section-overview .order-currency" : {
            "font-size" : "85%"
        },

        ".page-pne .infobox" :{
            "border" : "solid #c03030 1px"
        },

        ".pages-checkout .page-section-content" : {
            "background" : "#FFFFFF"
        },
        ".pages-checkout .page-section-overview" : {
            "background" : "white",
            "color" : "black"
        },
        ".pages-checkout .page-section-shopinfo" : {
            "background" : "white",
            "display":"none"
        },
        ".row .row-amount" : {
            "color" : "black"
        },
        ".pages-checkout" : {
            "color" : "#FFFFFF!important"
        },
        <?php echo $data['styles']?>
    };
    function checkoutInit(url, val) {
        $ipsp("checkout").scope(function() {
            this.setCheckoutWrapper("#checkout_wrapper");
            this.setModal(false);
            this.setCssStyle(checkoutStyles);
            this.width("100%");
            this.addCallback(__DEFAULTCALLBACK__);
            this.action("show", function(data) {
                jQuery("#checkout_loader").remove();
                jQuery("#checkout").show();
            });
            this.action("hide", function(data) {
                jQuery("#checkout").hide();
            });
            this.action("resize", function(data) {
                jQuery("#checkout_wrapper").height(data.height);
            });         
            this.loadUrl(url);
        });
    };
    checkoutInit('<?php echo $data['url']?>');
</script>