<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
   
	<li>
	<?php echo $this->__('You will be required to enter your payment details before you place an order.') ?>	   
    </li>
  <div style="max-width: 340px;display: flex;flex-flow: row wrap;justify-content: space-between;" class="flex-container">
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/csob.svg" alt="1" class="img-responsive"/>
        </div>
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/mbank.svg" alt="1" class="img-responsive"/>
        </div>
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/otp.svg" alt="1" class="img-responsive"/>
        </div>
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/pabk.svg" alt="1" class="img-responsive"/>
        </div>
    </div>
    <div style="margin-top: 10px; max-width: 340px;display: flex;flex-flow: row wrap;justify-content: space-between;"
         class="flex-container">
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/prima.svg" alt="1" class="img-responsive"/>
        </div>
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/sberbank.svg" alt="1" class="img-responsive"/>
        </div>
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/slsp.svg" alt="1" class="img-responsive"/>
        </div>
        <div style="margin: auto;margin-left: 0;" class="flex-item">
            <img width="65" src="{$this_path nofilter}img/banks/vub.svg" alt="1" class="img-responsive"/>
        </div>
    </div>
</ul>
