<fieldset class="form-list">
<ul>
   
	<li>
	<?php echo $this->__('You will be required to enter your payment details before you place an order. We accept: ') ?>	   
    </li>
	<div style="max-width: 235px;">
	<img style="float:left;" width="43px" height="26px" src="<?php echo $this->getSkinUrl('images/Fondy/visa.svg'); ?>" alt="visa">
	<img height="26px" src="<?php echo $this->getSkinUrl('images/Fondy/mastercard.svg'); ?>" alt="mastercard"> 
	<img height="26px" src="<?php echo $this->getSkinUrl('images/Fondy/Diners_Club_Logo3.svg'); ?>" alt="Diners_Club"> 
	<img height="26px" src="<?php echo $this->getSkinUrl('images/Fondy/discover.png'); ?>" alt="discover_logo"><br/>
	<img height="26px" src="<?php echo $this->getSkinUrl('images/Fondy/komercni-banka.jpg'); ?>" alt="komercni-banka"> 
	<img height="26px" src="<?php echo $this->getSkinUrl('images/Fondy/Raiffeisen-Polbank-logo.jpg'); ?>" alt="logo_en"> 
	<img height="22px" src="<?php echo $this->getSkinUrl('images/Fondy/Platba-24.png'); ?>" alt="Platba-24"> 
	</div>
</ul>
</fieldset>